[package]
org = "ballerina"
name = "url"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["url encoding", "url decoding"]
repository = "https://github.com/ballerina-platform/module-ballerina-url"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"

[[platform.java11.dependency]]
path = "../native/build/libs/url-native-@project.version@.jar"
