[package]
org = "ballerina"
name = "url"
version = "2.1.0"
authors = ["Ballerina"]
keywords = ["url encoding", "url decoding"]
repository = "https://github.com/ballerina-platform/module-ballerina-url"
license = ["Apache-2.0"]
distribution = "slbeta6"

[[platform.java11.dependency]]
path = "../native/build/libs/url-native-2.1.0-SNAPSHOT.jar"
